### ISSUE TITLE
How edit error message ?

### ISSUE THREAD

**Issue by SupchickCode** [mvanduijker/laravel-model-exists-rule#6]
I have this rule:

![image](https://user-images.githubusercontent.com/58991461/206179754-0979ab68-4a76-4602-b8df-821819e27e3e.png)

And validation error message looks like this `validation.model_exists`

I try to edit this message like this 
![image](https://user-images.githubusercontent.com/58991461/206180150-2c306460-3b6b-4142-9482-d37885f7ef43.png)

But nothing helps me

**Comment by mvanduijker** [comment]
In this test it's described how to do the translations https://github.com/mvanduijker/laravel-model-exists-rule/blob/master/tests/Unit/ModelExistsTest.php#L72 will that work for you?

I do see that the default translation in https://github.com/mvanduijker/laravel-model-exists-rule/blob/master/resources/lang/en/modelExists.php is incorrect.

But if you want completely different translations per rule, I think we have to make a change in this package. But I have to look it up.

**Comment by SupchickCode** [comment]
Thank u for reply

**Comment by jjjrmy** [comment]
bump for this, still having this issue
